// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuesday.Repositories;

namespace Tuesday.Migrations
{
    [DbContext(typeof(DbManager))]
    [Migration("20210305003718_zefzefsred")]
    partial class zefzefsred
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Tuesday.Entities.ExigenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExigenceType")
                        .HasColumnType("int");

                    b.Property<int?>("JalonID")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JalonID");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskEntityId");

                    b.ToTable("Exigence");
                });

            modelBuilder.Entity("Tuesday.Entities.JalonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RealEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealStartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Jalon");
                });

            modelBuilder.Entity("Tuesday.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealStartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("JalonId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RequiredTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("RequiredTaskId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Tuesday.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Clem",
                            LastName = "Laurain"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Olivier",
                            LastName = "Petrerella"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Hugo",
                            LastName = "Molle"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Henri",
                            LastName = "Michelon"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Julien",
                            LastName = "Drevron"
                        });
                });

            modelBuilder.Entity("Tuesday.Entities.ExigenceEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.JalonEntity", null)
                        .WithMany()
                        .HasForeignKey("JalonID");

                    b.HasOne("Tuesday.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuesday.Entities.TaskEntity", null)
                        .WithMany("Exigences")
                        .HasForeignKey("TaskEntityId");
                });

            modelBuilder.Entity("Tuesday.Entities.JalonEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuesday.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuesday.Entities.TaskEntity", "RequiredTask")
                        .WithMany()
                        .HasForeignKey("RequiredTaskId");

                    b.Navigation("RequiredTask");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.Navigation("Exigences");
                });
#pragma warning restore 612, 618
        }
    }
}
