// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuesday.Repositories;

namespace Tuesday.Migrations
{
    [DbContext(typeof(DbManager))]
    [Migration("20210303225957_Exigence5")]
    partial class Exigence5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Tuesday.Entities.ExigenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExigenceType")
                        .HasColumnType("int");

                    b.Property<int?>("JalonID")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JalonID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Exigence");
                });

            modelBuilder.Entity("Tuesday.Entities.JalonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Jalon");
                });

            modelBuilder.Entity("Tuesday.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("JalonId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RealStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RequiredTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("RequiredTaskId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskExigence", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("ExigenceId")
                        .HasColumnType("int");

                    b.HasKey("TaskId", "ExigenceId");

                    b.HasIndex("ExigenceId");

                    b.ToTable("TaskExigence");
                });

            modelBuilder.Entity("Tuesday.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Tuesday.Entities.ExigenceEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.JalonEntity", null)
                        .WithMany()
                        .HasForeignKey("JalonID");

                    b.HasOne("Tuesday.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tuesday.Entities.JalonEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuesday.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuesday.Entities.TaskEntity", "RequiredTask")
                        .WithMany()
                        .HasForeignKey("RequiredTaskId");

                    b.Navigation("RequiredTask");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskExigence", b =>
                {
                    b.HasOne("Tuesday.Entities.ExigenceEntity", "Exigence")
                        .WithMany("TaskExigences")
                        .HasForeignKey("ExigenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuesday.Entities.TaskEntity", "Task")
                        .WithMany("TaskExigences")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exigence");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Tuesday.Entities.ExigenceEntity", b =>
                {
                    b.Navigation("TaskExigences");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.Navigation("TaskExigences");
                });
#pragma warning restore 612, 618
        }
    }
}
