// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuesday.Repositories;

namespace Tuesday.Migrations
{
    [DbContext(typeof(DbManager))]
    partial class DbManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("asigneeId")
                        .HasColumnType("int");

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("label")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("plannedStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("realStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("requiredTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("asigneeId");

                    b.HasIndex("requiredTaskId");

                    b.ToTable("taskRepo");
                });

            modelBuilder.Entity("Tuesday.Entities.UtilisateurEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UtilisateurEntity");
                });

            modelBuilder.Entity("Tuesday.Entities.TaskEntity", b =>
                {
                    b.HasOne("Tuesday.Entities.UtilisateurEntity", "asignee")
                        .WithMany()
                        .HasForeignKey("asigneeId");

                    b.HasOne("Tuesday.Entities.TaskEntity", "requiredTask")
                        .WithMany()
                        .HasForeignKey("requiredTaskId");

                    b.Navigation("asignee");

                    b.Navigation("requiredTask");
                });
#pragma warning restore 612, 618
        }
    }
}
